language: go

go:
  - 1.16.7

before_install:
  - go mod tidy
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8f2e839e-1466-4912-871a-e1574ef160cb