language: go

go:
  - 1.16.7
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 69c14921-3f67-4304-b058-8c7321d80557